version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox

    steps:
      - checkout

      - run:
          name: Run tests
          command: tox -e coverage-report

      - run:
          name: Coverage
          command: |
            sudo pip install codecov
            codecov
  flake8:
    docker:
      - image: circleci/python:3-stretch

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_flake8.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_flake8.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_flake8.txt" }}
          paths:
            - "venv"

      - run:
          name: Run Flake8 checks
          command: |
            . venv/bin/activate
            flake8 admin_ip_restrictor

  deploy:
    docker:
      - image: circleci/python:3-stretch

    steps:
      - checkout
      - run:
          name: Push to PYPI
          command: make publish


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - flake8
      - deploy:
        requires:
          - build
          - flake8
        filters:
          branches:
            only:
              - master